//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CrazyCustomsEntity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CrazyCustomsProcessorEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CrazyCustomsProcessorEntities1 object using the connection string found in the 'CrazyCustomsProcessorEntities1' section of the application configuration file.
        /// </summary>
        public CrazyCustomsProcessorEntities() : base("name=CrazyCustomsProcessorEntities", "CrazyCustomsProcessorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CrazyCustomsProcessorEntities1 object.
        /// </summary>
        public CrazyCustomsProcessorEntities(string connectionString) : base(connectionString, "CrazyCustomsProcessorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CrazyCustomsProcessorEntities1 object.
        /// </summary>
        public CrazyCustomsProcessorEntities(EntityConnection connection) : base(connection, "CrazyCustomsProcessorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DockEntry> DockEntry
        {
            get
            {
                if ((_DockEntry == null))
                {
                    _DockEntry = base.CreateObjectSet<DockEntry>("DockEntry");
                }
                return _DockEntry;
            }
        }
        private ObjectSet<DockEntry> _DockEntry;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HSCodeDictionary> HSCodeDictionary
        {
            get
            {
                if ((_HSCodeDictionary == null))
                {
                    _HSCodeDictionary = base.CreateObjectSet<HSCodeDictionary>("HSCodeDictionary");
                }
                return _HSCodeDictionary;
            }
        }
        private ObjectSet<HSCodeDictionary> _HSCodeDictionary;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DockEntry EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDockEntry(DockEntry dockEntry)
        {
            base.AddObject("DockEntry", dockEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HSCodeDictionary EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHSCodeDictionary(HSCodeDictionary hSCodeDictionary)
        {
            base.AddObject("HSCodeDictionary", hSCodeDictionary);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CrazyCustomsProcessorModel", Name="DockEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DockEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DockEntry object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static DockEntry CreateDockEntry(global::System.Int32 id)
        {
            DockEntry dockEntry = new DockEntry();
            dockEntry.ID = id;
            return dockEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContainerNumber
        {
            get
            {
                return _ContainerNumber;
            }
            set
            {
                OnContainerNumberChanging(value);
                ReportPropertyChanging("ContainerNumber");
                _ContainerNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContainerNumber");
                OnContainerNumberChanged();
            }
        }
        private global::System.String _ContainerNumber;
        partial void OnContainerNumberChanging(global::System.String value);
        partial void OnContainerNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OperationName
        {
            get
            {
                return _OperationName;
            }
            set
            {
                OnOperationNameChanging(value);
                ReportPropertyChanging("OperationName");
                _OperationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OperationName");
                OnOperationNameChanged();
            }
        }
        private global::System.String _OperationName;
        partial void OnOperationNameChanging(global::System.String value);
        partial void OnOperationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OperationCode
        {
            get
            {
                return _OperationCode;
            }
            set
            {
                OnOperationCodeChanging(value);
                ReportPropertyChanging("OperationCode");
                _OperationCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OperationCode");
                OnOperationCodeChanged();
            }
        }
        private global::System.String _OperationCode;
        partial void OnOperationCodeChanging(global::System.String value);
        partial void OnOperationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Conveyance
        {
            get
            {
                return _Conveyance;
            }
            set
            {
                OnConveyanceChanging(value);
                ReportPropertyChanging("Conveyance");
                _Conveyance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Conveyance");
                OnConveyanceChanged();
            }
        }
        private global::System.String _Conveyance;
        partial void OnConveyanceChanging(global::System.String value);
        partial void OnConveyanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VoyageNumber
        {
            get
            {
                return _VoyageNumber;
            }
            set
            {
                OnVoyageNumberChanging(value);
                ReportPropertyChanging("VoyageNumber");
                _VoyageNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VoyageNumber");
                OnVoyageNumberChanged();
            }
        }
        private global::System.String _VoyageNumber;
        partial void OnVoyageNumberChanging(global::System.String value);
        partial void OnVoyageNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dock
        {
            get
            {
                return _Dock;
            }
            set
            {
                OnDockChanging(value);
                ReportPropertyChanging("Dock");
                _Dock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dock");
                OnDockChanged();
            }
        }
        private global::System.String _Dock;
        partial void OnDockChanging(global::System.String value);
        partial void OnDockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Target
        {
            get
            {
                return _Target;
            }
            set
            {
                OnTargetChanging(value);
                ReportPropertyChanging("Target");
                _Target = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Target");
                OnTargetChanged();
            }
        }
        private global::System.String _Target;
        partial void OnTargetChanging(global::System.String value);
        partial void OnTargetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Time;
        partial void OnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CrazyCustomsProcessorModel", Name="HSCodeDictionary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HSCodeDictionary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HSCodeDictionary object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        public static HSCodeDictionary CreateHSCodeDictionary(global::System.Int32 id, global::System.String code)
        {
            HSCodeDictionary hSCodeDictionary = new HSCodeDictionary();
            hSCodeDictionary.ID = id;
            hSCodeDictionary.Code = code;
            return hSCodeDictionary;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ManagementCondition
        {
            get
            {
                return _ManagementCondition;
            }
            set
            {
                OnManagementConditionChanging(value);
                ReportPropertyChanging("ManagementCondition");
                _ManagementCondition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ManagementCondition");
                OnManagementConditionChanged();
            }
        }
        private global::System.String _ManagementCondition;
        partial void OnManagementConditionChanging(global::System.String value);
        partial void OnManagementConditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExaminationCondition
        {
            get
            {
                return _ExaminationCondition;
            }
            set
            {
                OnExaminationConditionChanging(value);
                ReportPropertyChanging("ExaminationCondition");
                _ExaminationCondition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExaminationCondition");
                OnExaminationConditionChanged();
            }
        }
        private global::System.String _ExaminationCondition;
        partial void OnExaminationConditionChanging(global::System.String value);
        partial void OnExaminationConditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeclarationFactor
        {
            get
            {
                return _DeclarationFactor;
            }
            set
            {
                OnDeclarationFactorChanging(value);
                ReportPropertyChanging("DeclarationFactor");
                _DeclarationFactor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeclarationFactor");
                OnDeclarationFactorChanged();
            }
        }
        private global::System.String _DeclarationFactor;
        partial void OnDeclarationFactorChanging(global::System.String value);
        partial void OnDeclarationFactorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstUnitName
        {
            get
            {
                return _FirstUnitName;
            }
            set
            {
                OnFirstUnitNameChanging(value);
                ReportPropertyChanging("FirstUnitName");
                _FirstUnitName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstUnitName");
                OnFirstUnitNameChanged();
            }
        }
        private global::System.String _FirstUnitName;
        partial void OnFirstUnitNameChanging(global::System.String value);
        partial void OnFirstUnitNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondUnitName
        {
            get
            {
                return _SecondUnitName;
            }
            set
            {
                OnSecondUnitNameChanging(value);
                ReportPropertyChanging("SecondUnitName");
                _SecondUnitName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondUnitName");
                OnSecondUnitNameChanged();
            }
        }
        private global::System.String _SecondUnitName;
        partial void OnSecondUnitNameChanging(global::System.String value);
        partial void OnSecondUnitNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BestCountryRate
        {
            get
            {
                return _BestCountryRate;
            }
            set
            {
                OnBestCountryRateChanging(value);
                ReportPropertyChanging("BestCountryRate");
                _BestCountryRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BestCountryRate");
                OnBestCountryRateChanged();
            }
        }
        private global::System.String _BestCountryRate;
        partial void OnBestCountryRateChanging(global::System.String value);
        partial void OnBestCountryRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImportRate
        {
            get
            {
                return _ImportRate;
            }
            set
            {
                OnImportRateChanging(value);
                ReportPropertyChanging("ImportRate");
                _ImportRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImportRate");
                OnImportRateChanged();
            }
        }
        private global::System.String _ImportRate;
        partial void OnImportRateChanging(global::System.String value);
        partial void OnImportRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExportRate
        {
            get
            {
                return _ExportRate;
            }
            set
            {
                OnExportRateChanging(value);
                ReportPropertyChanging("ExportRate");
                _ExportRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExportRate");
                OnExportRateChanged();
            }
        }
        private global::System.String _ExportRate;
        partial void OnExportRateChanging(global::System.String value);
        partial void OnExportRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConsumeRate
        {
            get
            {
                return _ConsumeRate;
            }
            set
            {
                OnConsumeRateChanging(value);
                ReportPropertyChanging("ConsumeRate");
                _ConsumeRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ConsumeRate");
                OnConsumeRateChanged();
            }
        }
        private global::System.String _ConsumeRate;
        partial void OnConsumeRateChanging(global::System.String value);
        partial void OnConsumeRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddedValueTaxRate
        {
            get
            {
                return _AddedValueTaxRate;
            }
            set
            {
                OnAddedValueTaxRateChanging(value);
                ReportPropertyChanging("AddedValueTaxRate");
                _AddedValueTaxRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddedValueTaxRate");
                OnAddedValueTaxRateChanged();
            }
        }
        private global::System.String _AddedValueTaxRate;
        partial void OnAddedValueTaxRateChanging(global::System.String value);
        partial void OnAddedValueTaxRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DrawbackRate
        {
            get
            {
                return _DrawbackRate;
            }
            set
            {
                OnDrawbackRateChanging(value);
                ReportPropertyChanging("DrawbackRate");
                _DrawbackRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DrawbackRate");
                OnDrawbackRateChanged();
            }
        }
        private global::System.String _DrawbackRate;
        partial void OnDrawbackRateChanging(global::System.String value);
        partial void OnDrawbackRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion
    
    }

    #endregion
    
}
